sudo: false
matrix:
  include:
    - language: java
      cache:
        directories:
          - $HOME/.m2
      install:
        - mvn dependency:resolve
      script:
        - bash .travis-deploy.sh
      jdk:
        - openjdk7
        - openjdk8
        - oraclejdk8
      dist: trusty
      env:
        global:
          - secure: nQlyYKC19evsq9bOhouStXoZe47WekUqxmOhBBBEN6Sx/+FCagv6+vPJ4bTPip4pZoN7EH/1qYo2YRPWJw658jH0bcWobQJRK5SihbUODRaQW9/wIrxGFFlakRUz5bT3xfwiLPRvXW8GOeRHa+ZfPBaGPCEs7e/HdANGt98WgLcaeZ66cDMBEfK+ZK3P5KEbTqjNveJDC5LtLT+cBUJ83JuiNCE7+gEO9sfKUe3FBK/putd9eEwhx0D5Yl9V4i8X4wUTx94EF5zTIpWuPG8G50efOmqyE2ES9Ly6BO3zFD7/qJVw/mp4yF9pkt5IPJhsZXlbvd8cB4lmPTxCi+IsxcMb3zLhIzmxo4VVc/1BYC4zo6vNfYEcOERMBpdIvaHlfzwsLPOvtlmBs19YnUJdsGrGoD7h3LcZqjQsqsF+V8/WPk/uhsMMufNN/mNPf28aikz5hBmZPAUDboDf1Of6VpKSOH4V5I9cNwZKO+Rqy3bkik4PZ4E+B85YmE74C/SIcLNNTg1leYwtrfj+0/S+ZwElfZuJIgOdDwcGe/eVYRapWz5MXCUcRv+svns0evYBAJDtH5KN/MrpyMXszOUMqNUnZXPn+4Tre0l2DifrU4naj6EpvwTyp0S/yuPmEFTbAto/JdDLx4KMrc762hBdoCKD7tM+1ZaHWNbiDB4kfHk=
          - secure: e/XK6+FsXlWgfASK691HOaSGvwba8HcPZ7qjng5yxg28u3FDsyttMSat0r1ubPRMCSwjGGHzVg+Dvc8DgaZFDuQSFneT3nVpRyM9M5xNqbFaGEZA7Fh4R7jew/0+p3FwlbI71tOPN2Y/u/6ZX5Mk+0dGwvHCIAmJTJ6X73wN9+nVC3RilR+aM9Gqhh8yk0yu8QraRwlARLD+52HLW52GbdjUJPLqTRQ4+a1bNrq9XO/4irKnjQPq/2KU/m9gMd/29R3SeODxWslM5MXhUexPAHKgTjhIJaJ6gFWY14YRj7yqgtHUaHFpFMY5JYFznXCDhkIVMCuXaCHT5YlqxC2uClqnc4+pAythVcLZN4P03/TOeWOcxxnTNYJeux9XgfAaBnLOxFQHVFMRDMPdr7+11hmQet2rV0eSVM8rDag1bsXQCHwRlzaCKUwxk+Bt4mXdZFvVFB7/z7SWA7a+f2DUR9NgJZGq7zV4WAN8tQOOZftL4kKVm1ZA+NUacfuIFoBU5Fv2//B9d41qJnLtFrL2AE+AkdHV2n4B3hfgIx4dqnNKCV6cg2fYLNY87MNty+u004z5/scaOBwI4MH/owErD9NCgrgpm+wPnGm/kXjM3v0PteLje7T7FRJ2A59eGnDW+yBScRoBtZAuK4A8MUN9ajtxvO7ATGZcJ10uM7GjzV4=
    - language: node_js
      node_js:
        - "8"
      install:
        - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
        - install_checkers
      script:
        - print_modified_markdown_files
        - spellcheck --single
        - linkcheck
      cache:
        directories:
          - $(npm config get prefix)/lib/node_modules
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci